= Installation Guide
:toc:

== Prerequisites
Before you begin, ensure you have the following tools and dependencies
installed.

=== Install Python 3.7+ and Git
On Linux, Python and Git are typically pre-installed.
On macOS and Windows, you can use the https://www.python.org/downloads[official
Python installer].
Different options to install Git can be found https://git-scm.com/downloads[here].

=== Install Ninja
Ninja is a small build system with a focus on speed.
You should get Ninja using your
https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages[package
manager]
or download the https://github.com/ninja-build/ninja/releases[official release]
and put the `ninja` binary in your `PATH`.

=== Install Meson
Meson is an open source build system based on ninja meant to be both extremely
fast and, even more importantly, as user-friendly as possible.
Meson 0.63 or newer is required to build the different targets.
You can get meson through your package manager or by using pip:

[source,bash]
----
pip3 install --user meson
----

=== Verify Dependencies
To double-check if all dependencies are included in your `PATH`, run the
following commands:

[source,bash]
----
git --version
python3 --version
meson --version
ninja --version
----
Ensure that each command returns a version number as expected.

=== Get the Source Code
Use the git version control system to get a copy of the source code.

[source,bash]
----
git clone https://github.com/uviespace/airs-compression.git airspace
cd airspace
----


== Setup a Build Environment
Each build configuration uses a separate directory to maintain organization and
prevent conflicts between different build types. All build artifacts will be
generated within their respective directories.

=== Debug Build Setup
Create a `build_debug` directory for development and debugging, with debug
symbols enabled and optimizations disabled. This build is ideal for debugging
with GDB and development but will run slower:

[source,bash]
----
# Create debug build (--buildtype=debug is the default and can be omitted)
meson setup build_debug --buildtype=debug
cd build_debug
----

=== Release Build Setup
For production-ready builds with full optimizations (`-O3`), specify the
`--buildtype=release` flag during setup:

[source,bash]
----
meson setup build_release --buildtype=release
cd build_release
----


== Setup a Cross-Compilation Environment
Cross-compilation builds software on one machine (the build system) for
execution on a different target platform (the host system). Meson uses cross
files to specify the toolchain and target properties.
Supported cross files are located in the `cross/` directory of the project root.

=== Cross-Compilation Prerequisites
First install a cross-compiler toolchain for your target (e.g., the
https://www.gaisler.com/products/leon-bare-metal-cross-compiler[Gaisler BCC2
toolchain]) and add the toolchain's `bin` directory to your `PATH` so Meson can
find the compiler and other tools.

=== GR712RC Release Build with BCC2
For an optimized release build targeting the GR712RC processor, use the
following configuration:

[source,bash]
----
meson setup build_gr712rc_release \
  --cross-file=cross/bcc2-gcc-gr712rc.txt \
  --buildtype=plain \
  --optimization=2 \
  -Ddebug=false
cd build_gr712rc_release
----

Configuration options explained:

* `--cross-file`: Specifies the cross-compilation configuration
* `--buildtype=plain`: Allows manual control of optimization flags
* `--optimization=2`: Enables -O2 optimization level
* `-Ddebug=false`: Disables debug symbols and other information


== Configure a Build Environment
Meson allows you to configure various build options.
Use `meson configure` to list all available options, and meson configure
`-D<option>` to set specific options.
Here's an example enabling Address and Undefined Behavior Sanitizers:

[source,bash]
----
# First, cd in a build directory
cd <name of the build directory>
meson configure -Db_sanitize=address,undefined
----
For more information on sanitizers, visit the
https://clang.llvm.org/docs/AddressSanitizer.html[LLVM AddressSanitizer
documentation].


== Build Different Targets
Once you have set up a build directory, you need to change to it (if you have
not already done so) and then build the software.

=== Build the Compression Library
To build the compression library, run:

[source,bash]
----
ninja lib/libcmp.a
----
The resulting library `cmplib.a` will be located in the `lib` folder of your
build directory.

=== Build the AIRSPACE CLI
To build the xref:programs/README.adoc[CLI utility], run:

[source,bash]
----
ninja programs/airspace
----
The `airspace` binary will be located in the `programs` folder of your build
directory.

=== Build All Targets
To build all targets, simply run:

[source,bash]
----
ninja
----


== Testing

=== External dependencies
To run the unit tests you need a
https://www.ruby-lang.org/en/documentation/installation[Ruby interpreter],
to generate the test runners.

=== Run tests

[source,bash]
----
# First, cd in a build directory
cd <name of the build directory>

# Run all test
meson test

# List all available tests
meson test --list

# Run a single test
meson test <testname>

# Run a test under GDB
meson test --gdb <testname>
----

=== Producing a coverage report
Ensure that either `gcovr` or `lcov` is installed.

[source,bash]
----
# Enable coverage
cd <name of the build directory>
meson configure -Db_coverage=true

# Generate the coverage report
meson test  # or run the program you are interested in
ninja coverage-html

# If needed reset the coverage data
ninja clean-gcda
----

Find the report in the `meson-logs/coveragereport` subdirectory.
